name: Azure infrastructure provisioning - PROD

on:
  workflow_dispatch

jobs:

  infra_prod:
    name: Infrastructure provisioning
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      AAD_CURRENT_USER_AAD: ${{ secrets.CURRENT_AAD_USER_ID }}
      PAT: ${{ secrets.PAT }}
      ENVIRONMENT: "prod"
    steps:

      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Infrastructure provisioning
        shell: bash
        run: >

          # export TF_LOG="DEBUG"

          cd infrastructure

          terraform init

          terraform apply
          -var=tenant_id=${ARM_TENANT_ID}
          -var=service_principal_id=${ARM_CLIENT_ID}
          -var=client_secret=${ARM_CLIENT_SECRET}
          -var=subscription_id=${ARM_SUBSCRIPTION_ID}
          -var=current_aad_user_id=${AAD_CURRENT_USER_AAD}
          -var=github_token=${PAT}
          -var=illumina_dataset_sas_token="${{ secrets.ILLUMINA_SAS_TOKEN }}"
          -var=illumina_dataset_sas_uri="${{ secrets.ILLUMINA_SAS_URI }}"
          -var=databricks_admin_mail="${{ secrets.ADMIN_USER_MAIL }}"
          -var=environment=${ENVIRONMENT}
          -auto-approve

          terraform output
