name: Azure infrastructure decommissioning - PROD

on:
  workflow_dispatch

jobs:

  cleanup_prod:
    name: Infrastructure cleanup - PROD
    runs-on: ubuntu-latest
    environment: CLEAN_UP
    env:
      ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      AAD_CURRENT_USER_AAD: ${{ secrets.CURRENT_AAD_USER_ID }}
    permissions: write-all
    steps:

      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Decomissioning resources
        shell: bash
        run: >-

          cd infrastructure

          terraform init

          terraform destroy
          -var=tenant_id=${ARM_TENANT_ID}
          -var=current_aad_user_id=${AAD_CURRENT_USER_AAD}
          -var=service_principal_id=${ARM_CLIENT_ID}
          -auto-approve
